# Generated by Django 3.2.8 on 2021-10-14 23:07

from django.db import migrations, models
import steps.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=steps.storage_backends.PrivateMediaStorage(), upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(storage=steps.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
