# Generated by Django 3.2.8 on 2021-10-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_collection_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='key',
            field=models.URLField(),
        ),
    ]
