# Generated by Django 3.2.8 on 2021-10-15 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0005_alter_sticker_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='steps.collection'),
            preserve_default=False,
        ),
    ]
