# Generated by Django 3.2.8 on 2021-10-15 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0007_sticker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticker', to='steps.collection'),
        ),
    ]
