# Generated by Django 3.2.8 on 2021-10-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0008_alter_sticker_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='type',
            field=models.CharField(default='private', max_length=100),
            preserve_default=False,
        ),
    ]
