# Generated by Django 3.2.8 on 2021-11-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0010_profile_stickers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='rarity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stickers',
            field=models.ManyToManyField(related_name='stickers', to='steps.Sticker'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='key',
            field=models.CharField(max_length=100),
        ),
    ]
